version: '1'

services:

  db:
    image: 'postgres'
    container_name: 'diplom-db-container'
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=diplom-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  diplom-backend:
    image: 'diplom-backend-ms-image'
    container_name: 'diplom-backend-ms-container'
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network

  nginx:
    image: "diplom-nginx-image"
    container_name: 'diplom-nginx-container'
    ports:
      - "2004:2004"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - diplom-backend
    networks:
      - my-network

volumes:
  pgdata:
    external: true

networks:
  my-network:
    driver: bridge